---
kind: pipeline
type: kubernetes
name: "camunda"

platform:
  arch: amd64

steps:
  - name: test
    image: golang:1.16
    commands:
      - go test -v ./...
      - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - golangci-lint run --deadline=5m
